### ISSUE TITLE
.jar won't run

### ISSUE THREAD

**Issue by Andry34** [CeON/CERMINE#41]
Hi all,
Thank you for developing Cermine which I found very useful when I tried it on the web.
I 've downloaded the stand alone version. I wanted to use it on windows 10 (64 bit) but it did not execute. Note that I have over jar executable which launch normally with a double click. 
Thank you for your responses.

**Comment by dtkaczyk** [comment]
@Andry34 CERMINE is intended to be used as a command line tool rather than through a traditional GUI. I am not familiar with Windows, but I believe you should be able to use its Command Prompt for this. The most typical use case assumes there is a collection of documents in PDF format and CERMINE's JAR is executed with `java` command in order to extract the metadata from each file. You will find the details on the exact command in the README.

**Comment by Andry34** [comment]
@dtkaczyk . Thanks for your response. I'll try (again) with your advices and I'll read carefully the readme.
GBY.
