### ISSUE TITLE
Extract arXiv identifier

### ISSUE THREAD

**Issue by tobiasdiez** [CeON/CERMINE#43]
The articles on the arXiv ([for example this thesis](https://arxiv.org/pdf/1405.2249.pdf)) contain a side-label containing the identifier (eg, arXiv:1405.2249v1  [math-ph]  9 May 2014). It would be nice if CERMINE could read and parse this information.

The different formats for the arXiv ids are discussed in the [official help](https://arxiv.org/help/arxiv_identifier).

**Comment by dtkaczyk** [comment]
The biggest problem with this is that the identifier is rotated 90 degrees with respect to the majority of the text. Currently, CERMINE does not support extraction of such fragments. Since is not trivial to implement, and we lack resources, I don't think this will happen any time soon. I will get back to this issue if the situation changes.
