### ISSUE TITLE
Problem with a two column paper

### ISSUE THREAD

**Issue by lukedickens** [CeON/CERMINE#54]
Hi,

I have had problems with the following paper using version 1.13 of the standalone tool:

Maximizing the Spread of Influence through a Social Network (2003) by
David Kempe, Jon Kleinberg, Éva Tardos
[https://www.cs.cornell.edu/home/kleinber/kdd03-inf.pdf](url)

It only extracts references in the left column of the last page. It seems to extract the right hand column of the body text, but fails on the references section.

Thanks

**Comment by dtkaczyk** [comment]
@lukedickens Sorry for answering so late. Such problems are typically caused by CERMINE's internal classifiers errors. We are using supervised machine learning for this, which in general is not trivial to debug and correct. It is also important to remember that CERMINE's results will never be 100% correct.

One solution could be to gather similar examples to this problematic one and extend the training sets. Unfortunately, we currently do not have resources to work on such tasks and in general, and therefore we do not address them.
