### ISSUE TITLE
Invalid reference section recognition

### ISSUE THREAD

**Issue by marekhorst** [CeON/CERMINE#55]
As reported in _OpenAIRE portal feedback system_ metadata extracted from the following thesis:

http://ria.ua.pt/bitstream/10773/1682/1/2009001399.pdf

contained invalid _bibliographic references_ section. 

I just confirmed it after uploading mentioned publication to:

http://cermine.ceon.pl/index.html

and receiving:

```
  <back>
    <ref-list>
      <ref id="ref1">
        <mixed-citation>
          <article-title>am ro A p m t p 9 i t f</article-title>
        </mixed-citation>
      </ref>
    </ref-list>
  </back>
```
or:
```
  <back>
    <ref-list>
      <ref id="ref1">
        <mixed-citation>9 i t f</mixed-citation>
      </ref>
    </ref-list>
  </back>
```
interchangeably, as a part of NLM. 

It looks like the table from _annex 1_ was interpreted as a part of bibliographic references.

**Comment by dtkaczyk** [comment]
Currently we do not really process theses (the models were trained on regular scientific articles only). This causes issues, especially when the layout or order of elements is somewhat unusual, which was the case here I believe. Since we don't have resources right now to prepare the system for such situations, there's nothing I can do.

I will close this issue, however, there is a related issue #44 (Support thesis's and books), which will remain open and wait for better times.
