### ISSUE TITLE
Problem extracting abstract to jats

### ISSUE THREAD

**Issue by eitanf** [CeON/CERMINE#60]
The attached paper parses just fine to text or zones, but trying to parse it to jats completely skips the abstract.
[CIDR_17_020.pdf](https://github.com/CeON/CERMINE/files/1369548/CIDR_17_020.pdf)

**Comment by dtkaczyk** [comment]
@eitanf  Sorry for answering so late. Such problems are typically caused by CERMINE's internal classifiers errors. We are using supervised machine learning for this, which in general is not trivial to debug and correct. It is also important to remember that CERMINE's results will never be 100% correct.

One solution could be to gather similar examples to this problematic one and extend the training sets. Unfortunately, we currently do not have resources to work on such tasks and therefore we do not address them.
