### ISSUE TITLE
make cermine interruptible to allow interruption in batch processing

### ISSUE THREAD

**Issue by marekhorst** [CeON/CERMINE#7]
We are heavily relying on cermine in IIS and unfortunately every now and then malicious PDF file appears taking huge amount of time to process.

Currently we have adjusted hadoop mapper (by overwriting `mapred.task.timeout` for `metadataextraction` module) to wait 60 minutes before assuming task does not respond. Apparently this is not enough. Recently after adding ~400k new PDF contents to `ObjectStore` cermine got files taking over 60 minutes to process each one of them. This causes whole IIS processing failure and the only way to proceed is to blacklist given document, retry IIS execution and hope we won't need to do this again (but we probably will).

One possible solution is to execute cermine processing in dedicated thread and interrupt it before the time defined in `mapred.task.timeout` passes. Currently this won't have any effect because cermine does not honor interruption. If you could check every now and then on `Thread.interrupted()`, probably as a part of loop condition check, then we could stop `metadataextraction` worker thread and continue with processing other documents.

Up until now my perception was that iText library blocks the execution which could be dead end. But after running `visualVM` profiler on cermine I realized there is no single method blocked for ages but the execution time of several methods changes interchangeably. This gives us opportunity to check whether thread was interrupted. 

Take a look at the attachment with `metadataextraction` CPU-time profiling the methods taking most of the execution time. This could guide us where to check for interruption.

![0074b6798a689a8ea05f0f292b0d2ae5_after_1h](https://cloud.githubusercontent.com/assets/11537389/11930686/16a0388c-a7e6-11e5-8da8-b677caf39473.png)

![0074b6798a689a8ea05f0f292b0d2ae5_after_1h_snapshot_calltree](https://cloud.githubusercontent.com/assets/11537389/11930695/21d992e8-a7e6-11e5-901a-11e5b0f31f5f.png)

**Comment by mwojnars** [comment]
Same problem occurs occassionally in Paperity. I would suggest adding a command-line parameter to CERMINE, say, "timeout", such that CERMINE can control the execution time internally and terminate when the timeout passes. In this approach, there is likely no need for using threads to control the timeout, just doing a periodical time check in a key loop of the pdf processing routine and raising an exception when the timeout passes.

**Comment by mkobos** [comment]
I introduced the timeout facility in #20.

Here I'll present design considerations that led to this solution and some comments related to testing the solution. 

# Design considerations

Two options were considered when implementing the timeout functionality:

1. **separate JVM**: the processing code that should be prone to being interrupted by the timeout would be run in a separate JVM. That separate JVM process would be killed when the timeout deadline passed.
2. **check points**: check points would be inserted into the existing processing code. They would check whether the timeout deadline passed and if so, they would throw an exception.

The **"check points" approach was chosen**, mainly because of its simplicity. However, here are the disadvantages of both solutions:

**Disadvantages of separate JVM approach**:

- Resources issues: starting two JVMs - one corresponding to the code that the user interacts with directly and one for the processing that might be interrupted by a timeout - would require more startup time and more memory.
- A lot of brittle boilerplate code that would allow for communication between two JVMs would have to be created and maintained.
- It might not be obvious to decide which parts of code should be run in which JVM.
- Completely clean exit from the processing code would not be possible (since the whole JVM process would be killed).

**Disadvantages of check points approach**:

- It’s virtually impossible to guarantee that the program ends in given time. This is because of two issues.
  - A CERMINE developer might have introduced some long-running code without inserting timeout check point inside it.
  -  It’s possible that there are some PDF documents where the processing time takes a lot of time in parts of the code that don’t have check points in them yet since I executed the tests and introduced the check points based on a certain sample of PDF files.
- Maintaining the timeout functionality when a new code is introduced is difficult. This is because in general, you don't know where the program will spend most of its processing time, i.e. you don't know where the hot spots are. 
  - Ideally, after adding some new code you would run the program on a batch of sample of PDF files with a profiler-like tool and **look for hot spots in the code** and then put check points inside them.
  - You would also run a tool that checks what is the **real-life resolution of timeouts** after introducing the new code. If the resolution is high, the processing stops almost immediately after given time passes, no matter what the actual value of the timeout is; if the resolution is low, the processing does not stop immediately and the actual stop time might heavily depend on the actual value of the timeout. After introducing the new code the resolution might become lower; in such case some additional check points should be introduced.
- The resolution depends on the speed of the computer (the faster the computer, the higher resolution) and the complexity of the document (the more complex the document, the lower resolution because the longer time various processing steps take).

# Testing the solution

When testing the solution in practice, I used 1) **a random sample of 100 PDF documents** processed by OpenAIRE system's inference subsystem called IIS  and 2) a **complex PDF file** which took the IIS system very long to process using CERMINE (the file is a part of the source code now here: `cermine-impl/src/test/resources/pl/edu/icm/cermine/tools/timeout/complex.pdf`). I made sure that the resolution of timeouts on these files is appropriate (i.e. that it doesn't take more than 1-2 seconds to stop the application after the timeout deadline passes). As discussed with @dtkaczyk elsewhere, it would be nice to implement tests like these as integration tests.

**Comment by mkobos** [comment]
I updated the "Testing the solution" section in the above comment https://github.com/CeON/CERMINE/issues/7#issuecomment-220559827 to reflect the fact that I tested the solution on additional complex PDF files.

**Comment by mkobos** [comment]
@dkaczyk: do you think that we can close this ticket?

**Comment by mwojnars** [comment]
Which CERMINE version contains this change and how to use it (is there a command-line parameter)? Does it work with PdfNLMContentExtractor class?

**Comment by mkobos** [comment]
@mwojnars: It works with all user-facing classes and there's a command-line parameter as you requested. I don't know about the version though -

**Comment by dtkaczyk** [comment]
@mwojnars: Timeout functionality can be found in the latest snapshot (1.10). It works with the newer [ContentExtractor class](https://github.com/CeON/CERMINE/blob/master/cermine-impl/src/main/java/pl/edu/icm/cermine/ContentExtractor.java), from the command line as well. For example this will extract: document metadata in JATS format ("-output jats"), and labelled textual zones ("-output zones"):

`java -cp cermine-impl-1.10-20160717.210009-6-jar-with-dependencies.jar pl.edu.icm.cermine.ContentExtractor -path path/to/pdfs -output jats,zones -timeout 60`

Classes Pdf*Extractor are now deprecated, and all the neccessary updates and extensions will be done in ContentExtractor only.

**Comment by dtkaczyk** [comment]
@mwojnars: Did you have time to test this functionality? Our tests on large collections in OpenAIRE system suggest it works as expected.

**Comment by mwojnars** [comment]
We upgraded in the meantime to a newer version of CERMINE where execution times dropped to a normal time of several seconds, so finally we didn't have a need to try timeout. If the problem re-occurs we'll check it.

**Comment by dtkaczyk** [comment]
Thanks for the update. I am closing this issue for now, if any problems occur again, i'll reopen it.
